/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto03;

import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class Projeto03 extends javax.swing.JFrame {

    /**
     * Creates new form Projeto03
     */
    public Projeto03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExibe = new javax.swing.JButton();
        cbVogais = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExibe.setText("Exibe");
        btnExibe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibeActionPerformed(evt);
            }
        });

        cbVogais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "a", "E", "e", "I", "i", "O", "o", "U", "u" }));
        cbVogais.setSelectedIndex(-1);
        cbVogais.setSelectedItem(-1);

        jLabel1.setText("Selecione uma vogal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbVogais, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExibe)
                        .addGap(9, 9, 9)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVogais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addComponent(btnExibe)
                .addGap(121, 121, 121))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibeActionPerformed
        // TODO add your handling code here:
        
        String vogal = "";
        int op = cbVogais.getSelectedIndex();
        
        if (op == 0)
             vogal = "A";
        if (op == 1)
             vogal = "a";
        if (op == 2)
             vogal = "E";
        if (op == 3)
             vogal = "e";
        if (op == 4)
             vogal = "I";
        if (op == 5)
             vogal = "i";
        if (op == 6)
             vogal = "O";
        if (op == 7)
             vogal = "o";
        if (op == 8)
             vogal = "U";
        if (op == 9)
             vogal = "u";
        
        String tipo = vogal.equals(vogal.toUpperCase()) ? "maiúscula" : "minúscula";
        
        if (vogal.equalsIgnoreCase("A"))
            JOptionPane.showMessageDialog(null, "Você escolheu a vogal " + vogal + " (" + tipo + ").");
        else if (vogal.equalsIgnoreCase("E"))
            JOptionPane.showMessageDialog(null, "Você escolheu a vogal " + vogal + " (" + tipo + ").");
        else if (vogal.equalsIgnoreCase("I"))
            JOptionPane.showMessageDialog(null, "Você escolheu a vogal " + vogal + " (" + tipo + ").");
        else if (vogal.equalsIgnoreCase("O"))
            JOptionPane.showMessageDialog(null, "Você escolheu a vogal " + vogal + " (" + tipo + ").");
        else if (vogal.equalsIgnoreCase("U"))
            JOptionPane.showMessageDialog(null, "Você escolheu a vogal " + vogal + " (" + tipo + ").");
    }//GEN-LAST:event_btnExibeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projeto03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projeto03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projeto03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projeto03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExibe;
    private javax.swing.JComboBox<String> cbVogais;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
