/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto01;

import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class Projeto01 extends javax.swing.JFrame {

    /**
     * Creates new form Projeto01
     */
    public Projeto01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTemp = new javax.swing.JComboBox<>();
        btnConverte = new javax.swing.JButton();
        btnLimpa = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Informe uma temperatura");

        jLabel2.setText("Selecione a escala ");

        cbTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahreinheit", "Kelvin" }));
        cbTemp.setSelectedIndex(-1);
        cbTemp.setSelectedItem(-1);
        cbTemp.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                cbTempComponentRemoved(evt);
            }
        });
        cbTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTempActionPerformed(evt);
            }
        });

        btnConverte.setText("Converter");
        btnConverte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverteActionPerformed(evt);
            }
        });

        btnLimpa.setText("Limpar");
        btnLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpaActionPerformed(evt);
            }
        });

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConverte)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnLimpa))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConverte)
                    .addComponent(btnLimpa))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTempComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbTempComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTempComponentRemoved

    private void cbTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTempActionPerformed

    private void btnConverteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverteActionPerformed
        // TODO add your handling code here:
        try{
            double temp = Double.parseDouble(txtValor.getText());
            //int op = Integer.parseInt(cbTemp.toString());
            int op = cbTemp.getSelectedIndex();
            
            if (op == 0)
                selCelsius(temp);
            if (op == 1)
                 selFah(temp);
            if (op == 2)
                selKelvin(temp);    
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Informe um valor válido", "erro", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnConverteActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpaActionPerformed
        // TODO add your handling code here:
        txtValor.setText("");
        cbTemp.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimpaActionPerformed
    
    public void selCelsius(double temp){
        double k = temp + 273.15; 
        double f = (temp * 9/5) + 32;
        StringBuilder resultado = new StringBuilder();
        resultado.append("Kelvin: ").append(String.format("%.2f K", k)).append("\n");
        resultado.append("Fahrenheit: ").append(String.format("%.2f °F", f));
        JOptionPane.showMessageDialog(null, resultado);
    }
    
    public void selKelvin(double temp){
        double c = temp - 273.15;
        double f = (c * 9/5) + 32;
        StringBuilder resultado = new StringBuilder();
        resultado.append("Celsius: ").append(String.format("%.2f °C", c)).append("\n");
        resultado.append("Fahrenheit: ").append(String.format("%.2f °F", f));
        JOptionPane.showMessageDialog(null, resultado);
    }
    
    public void selFah(double temp){
        double c = (temp - 32) * 5/9;
        double k = c + 273.15;
        StringBuilder resultado = new StringBuilder();
        resultado.append("Celsius: ").append(String.format("%.2f °C", c)).append("\n");
        resultado.append("Kelvin: ").append(String.format("%.2f K", k));
        JOptionPane.showMessageDialog(null, resultado);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projeto01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projeto01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projeto01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projeto01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConverte;
    private javax.swing.JButton btnLimpa;
    private javax.swing.JComboBox<String> cbTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
